### ISSUE TITLE
Error while starting, can i get full install guide?

### ISSUE THREAD

**Issue by xxxNEXON** [pietrzakadrian/bank#12]
/var/www/html/bank/server/config/db.config.js:10
    max: env.pool.max,
                  ^

TypeError: Cannot read property 'max' of undefined
    at Object.<anonymous> (/var/www/html/bank/server/config/db.config.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/html/bank/server/index.js:29:12)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

**Comment by dudeisbrendan03** [comment]
Same issue 🤷‍♀️

**Comment by dudeisbrendan03** [comment]
Can you try and send the output of the following:
- Adding this to `env.config.js` under the `env` object:
```Javascript
pool: {
       max: 100,
       min: 100,
       acquire: 100,
       evict: 100,
       idle: 100,
     },
```
- The output of `node -v`

**Comment by pietrzakadrian** [comment]
I work on version 1.1, which in a sensible way divides this app on the frontend and backend. I am asking you for a week of patience.

**Comment by pietrzakadrian** [comment]
Problem has been solved. I wrote a new readme.me

**Comment by dudeisbrendan03** [comment]
Woop, looking forward to testing
