### ISSUE TITLE
 Objects are not valid as a React child 

### ISSUE THREAD

**Issue by dudeisbrendan03** [pietrzakadrian/bank#13]
```javascript
utils.js?12fe:225 uncaught at loadCurrency Error: Objects are not valid as a React child (found: TypeError: Failed to fetch). If you meant to render a collection of children, use an array instead.
    in div (created by RegisterPage)
    in form (created by RegisterPage)
    in span (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in RegisterPage (created by Connect(RegisterPage))
    in Connect(RegisterPage) (created by withSaga(Connect(RegisterPage)))
    in withSaga(Connect(RegisterPage)) (created by withReducer(withSaga(Connect(RegisterPage))))
    in withReducer(withSaga(Connect(RegisterPage))) (created by Route)
    in Route (created by withRouter(withReducer(withSaga(Connect(RegisterPage)))))
    in withRouter(withReducer(withSaga(Connect(RegisterPage)))) (created by WithStyles(withRouter(withReducer(withSaga(Connect(RegisterPage))))))
    in WithStyles(withRouter(withReducer(withSaga(Connect(RegisterPage))))) (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in App
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter)
    in SnackbarProvider
    in IntlProvider (created by LanguageProvider)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider)
    in MuiThemeProviderOld
    in Provider
Invariant Violation: Objects are not valid as a React child (found: TypeError: Failed to fetch). If you meant to render a collection of children, use an array instead.
    in div (created by RegisterPage)
    in form (created by RegisterPage)
    in span (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in div (created by RegisterPage)
    in RegisterPage (created by Connect(RegisterPage))
    in Connect(RegisterPage) (created by withSaga(Connect(RegisterPage)))
    in withSaga(Connect(RegisterPage)) (created by withReducer(withSaga(Connect(RegisterPage))))
    in withReducer(withSaga(Connect(RegisterPage))) (created by Route)
    in Route (created by withRouter(withReducer(withSaga(Connect(RegisterPage)))))
    in withRouter(withReducer(withSaga(Connect(RegisterPage)))) (created by WithStyles(withRouter(withReducer(withSaga(Connect(RegisterPage))))))
    in WithStyles(withRouter(withReducer(withSaga(Connect(RegisterPage))))) (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in App
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter)
    in SnackbarProvider
    in IntlProvider (created by LanguageProvider)
    in LanguageProvider (created by Connect(LanguageProvider))
    in Connect(LanguageProvider)
    in MuiThemeProviderOld
    in Provider
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:55:15)
    at throwOnInvalidObjectType (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12336:5)
    at reconcileChildFibers (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13110:7)
    at reconcileChildren (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13505:28)
    at updateHostComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13849:3)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14494:14)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17014:12)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17054:24)
    at renderRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17133:7)
    at performWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17993:7)
```

I pulled, ran npm install then start. Tried on node 8/9 and 10. All have the same result. 

I managed to get the same problem locally and when deploying to heroku.

It builds, starts but the trying to do anything breaks it.

Also how do you sign in as an admin/is there an admin control panel?

**Comment by dudeisbrendan03** [comment]
What version of node is `https://bank.pietrzakadrian.com/` running on?

**Comment by dudeisbrendan03** [comment]
Branch `1.1` works fine, but most the features are locked and I have no idea how to use admin.

**Comment by pietrzakadrian** [comment]
I work on version 1.1, which in a sensible way divides this app on the frontend and backend. I am asking you for a week of patience.

**Comment by pietrzakadrian** [comment]
Problem has been solved. I wrote a new readme.me
