### ISSUE TITLE
Error start backend

### ISSUE THREAD

**Issue by Fi1osof** [pietrzakadrian/bank#15]
I created .env from env.example, run npm i, then run npm start. Got:
```
npm start

> typescript-express-typeorm-boilerplate@1.0.0 start /disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend
> ts-node src/index.ts


/disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/controllers/users.controller.ts(55,68): error TS2339: Property 'login' does not exist on type 'Params'.
  Property 'login' does not exist on type 'string[]'.
src/controllers/users.controller.ts(108,68): error TS2339: Property 'email' does not exist on type 'Params'.
  Property 'email' does not exist on type 'string[]'.

    at createTSError (/disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/disk_kingstone/var/www/external/pietrzakadrian/bank/bank/backend/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-express-typeorm-boilerplate@1.0.0 start: `ts-node src/index.ts`

```

**Comment by pietrzakadrian** [comment]
done. https://github.com/pietrzakadrian/bank/commit/5d4194c9b21b30185552c6e674e9763982fcd00e
