### ISSUE TITLE
yarn start not working 

### ISSUE THREAD

**Issue by abdolim** [pietrzakadrian/bank#17]
$ yarn start
yarn run v1.17.3

           ^
TSError: ⨯ Unable to compile TypeScript:
src/services/users.service.ts:13:27 - error TS2589: Type instantiation is excess
ively deep and possibly infinite.

13     this.userRepository = getManager().getRepository(User);
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (E:\bank\backend\node_modules\ts-node\src\index.ts:245:12)
    at reportTSError (E:\bank\backend\node_modules\ts-node\src\index.ts:249:19)
    at getOutput (E:\bank\backend\node_modules\ts-node\src\index.ts:362:34)
    at Object.compile (E:\bank\backend\node_modules\ts-node\src\index.ts:395:32)
    at Module.m._compile (E:\bank\backend\node_modules\ts-node\src\index.ts:473:
43)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\bank\backend\
node_modules\ts-node\src\index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by dhuang612** [comment]
front end or backend?
Did you follow the steps on the readme?

**Comment by abdolim** [comment]
backend 
yes i followed the steps

**Comment by pietrzakadrian** [comment]
Hello @abdolim,

I'm looking for a solution to your problem. I tested the repository on all operating systems and no problem for now.

**Comment by abdolim** [comment]
i faced another problem 

           ^
TSError: ⨯ Unable to compile TypeScript:
src/services/users.service.ts:13:27 - error TS2589: Type instantiation is excess
ively deep and possibly infinite.

13     this.userRepository = getManager().getRepository(User);
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (E:\bank\backend\node_modules\ts-node\src\index.ts:245:12)
    at reportTSError (E:\bank\backend\node_modules\ts-node\src\index.ts:249:19)
    at getOutput (E:\bank\backend\node_modules\ts-node\src\index.ts:362:34)
    at Object.compile (E:\bank\backend\node_modules\ts-node\src\index.ts:395:32)
    at Module.m._compile (E:\bank\backend\node_modules\ts-node\src\index.ts:473:
43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (E:\bank\backend\
node_modules\ts-node\src\index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info

**Comment by sagardave17** [comment]
@pietrzakadrian, I am also facing same issue.

`λ yarn start                                                                                                                      
yarn run v1.17.3                                                                                                                  
warning package.json: No license field                                                                                            
$ ts-node src/index.ts                                                                                                            
                                                                                                                                  
C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:245                                                                 
    return new TSError(diagnosticText, diagnosticCodes)                                                                           
           ^                                                                                                                      
TSError: ⨯ Unable to compile TypeScript:                                                                                          
src/services/users.service.ts:13:27 - error TS2589: Type instantiation is excessively deep and possibly infinite.                 
                                                                                                                                  
13     this.userRepository = getManager().getRepository(User);                                                                    
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                     
                                                                                                                                  
    at createTSError (C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:245:12)                                       
    at reportTSError (C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:249:19)                                       
    at getOutput (C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:362:34)                                           
    at Object.compile (C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:395:32)                                      
    at Module.m._compile (C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:473:43)                                   
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)                                                             
    at Object.require.extensions.<computed> [as .ts] (C:\laragon\www\bank\backend\node_modules\ts-node\src\index.ts:476:12)       
    at Module.load (internal/modules/cjs/loader.js:628:32)                                                                        
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)                                                              
    at Module.require (internal/modules/cjs/loader.js:666:19)                                                                     
error Command failed with exit code 1.                                                                                            
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                              `

**Comment by pietrzakadrian** [comment]
done. https://github.com/pietrzakadrian/bank/commit/f0948bab5c811dba3bdd7f7c5d44bea665408555
